export const DummyVideos = [
  {
    id: 1,
    width: 1920,
    height: 1080,
    url: 'https://www.pexels.com/video/some-video-123456/',
    image: 'https://www.pexels.com/photo/some-image-123456/',
    duration: 10,
    user: {
      name: 'Username',
      url: 'https://www.pexels.com/@username',
    },
    video_files: [
      {
        id: 1,
        quality: 'HD',
        file_type: 'video/mp4',
        width: 1920,
        height: 1080,
        link: 'https://www.pexels.com/video/drops-of-liquid-on-a-tray-to-be-use-as-samples-3195394/',
      },
      {
        id: 2,
        quality: 'SD',
        file_type: 'video/mp4',
        width: 1280,
        height: 720,
        link: 'https://static.videezy.com/system/resources/previews/000/052/918/original/21.mp4',
      },
    ],
    tags: ['adventure', 'nature', 'outdoor'],
  },
  {
    id: 2,
    width: 1920,
    height: 1080,
    url: 'https://www.pexels.com/video/another-video-789012/',
    image: 'https://www.pexels.com/photo/another-image-789012/',
    duration: 9,
    user: {
      name: 'AnotherUser',
      url: 'https://www.pexels.com/@anotheruser',
    },
    video_files: [
      {
        id: 3,
        quality: 'HD',
        file_type: 'video/mp4',
        width: 1920,
        height: 1080,
        link: 'https://www.pexels.com/video/drops-of-liquid-on-a-tray-to-be-use-as-samples-3195394/',
      },
      {
        id: 4,
        quality: 'SD',
        file_type: 'video/mp4',
        width: 1280,
        height: 720,
        link: 'https://static.videezy.com/system/resources/previews/000/052/918/original/21.mp4',
      },
    ],
    tags: ['travel', 'landscape', 'mountains'],
  },
  {
    id: 3,
    width: 1920,
    height: 1080,
    url: 'https://www.pexels.com/video/another-video-789012/',
    image: 'https://www.pexels.com/photo/another-image-789012/',
    duration: 8,
    user: {
      name: 'AnotherUser',
      url: 'https://www.pexels.com/@anotheruser',
    },
    video_files: [
      {
        id: 4,
        quality: 'HD',
        file_type: 'video/mp4',
        width: 1920,
        height: 1080,
        link: 'https://www.pexels.com/video/drops-of-liquid-on-a-tray-to-be-use-as-samples-3195394/',
      },
      {
        id: 5,
        quality: 'SD',
        file_type: 'video/mp4',
        width: 1280,
        height: 720,
        link: 'https://static.videezy.com/system/resources/previews/000/052/918/original/21.mp4',
      },
    ],
    tags: ['travel', 'landscape', 'mountains'],
  },
  {
    id: 4,
    width: 1920,
    height: 1080,
    url: 'https://www.pexels.com/video/another-video-789012/',
    image: 'https://www.pexels.com/photo/another-image-789012/',
    duration: 8,
    user: {
      name: 'AnotherUser',
      url: 'https://www.pexels.com/@anotheruser',
    },
    video_files: [
      {
        id: 6,
        quality: 'HD',
        file_type: 'video/mp4',
        width: 1920,
        height: 1080,
        link: 'https://www.pexels.com/video/drops-of-liquid-on-a-tray-to-be-use-as-samples-3195394/',
      },
      {
        id: 7,
        quality: 'SD',
        file_type: 'video/mp4',
        width: 1280,
        height: 720,
        link: 'https://static.videezy.com/system/resources/previews/000/052/918/original/21.mp4',
      },
    ],
    tags: ['travel', 'landscape', 'mountains'],
  },
];
